# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["reid.butler+compute@fastly.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-default"
description = ""
language = "rust"
manifest_version = 3
name = "stepdex"
service_id = "1qNKGgI1CiwoSL0vxoSmlD"

[local_server]

[scripts]
  build = "cargo build --profile release"
